![](http://b-ssl.duitang.com/uploads/item/201808/24/20180824050055_nihnc.gif)

In [1]:
import numpy as np

In [3]:
# 空值
a = np.array([1,3,5,7,9,11,2,np.NAN])
a

array([ 1.,  3.,  5.,  7.,  9., 11.,  2., nan])

In [4]:
a.sum()

nan

In [6]:
np.nansum(a)

38.0

In [7]:
b = a + 10
np.corrcoef(a,b)

array([[nan, nan],
       [nan, nan]])

'''
np.corrcoef(a,b)的输出是相关系数矩阵
即：
   a   b 
a  1   1
b  1   1
'''

In [9]:
a[-1] = 13
b = a + 10
np.corrcoef(a,b)

array([[1., 1.],
       [1., 1.]])

In [12]:
c = a + np.random.randint(1,13,size = a.shape)
np.corrcoef(a,c)

array([[1.        , 0.78445069],
       [0.78445069, 1.        ]])

In [13]:
'''
numpy中统计学：
   平均值、中位数、方差、标准差、协方差、关联（相关性系数）
'''

'\nnumpy中统计学：\n   平均值、中位数、方差、标准差、协方差、关联（相关性系数）\n'

In [14]:
# 直方图统计数据出现的频次
nd = np.random.randint(0,999,size = 100)
np.histogram(nd,bins = 10)

(array([ 8, 10,  8, 18, 13,  9, 10,  6,  8, 10], dtype=int64),
 array([ 13. , 111.5, 210. , 308.5, 407. , 505.5, 604. , 702.5, 801. ,
        899.5, 998. ]))

文件操作

In [17]:
data = np.random.normal(loc = 65,scale = 3,size = 72).round(1)
data

array([66.5, 64.5, 58.5, 67.9, 62.5, 61.6, 63.5, 62.2, 68.6, 64.7, 67.5,
       60.9, 59.4, 62.1, 71.3, 59.7, 69.6, 64.6, 65.2, 57.5, 66.8, 63.9,
       66.7, 70.1, 65.3, 60.2, 61. , 59.9, 68.6, 67.1, 66.6, 66.8, 69.9,
       66.8, 66. , 63.4, 66.9, 62.3, 60.4, 62.7, 62.2, 65.4, 64. , 64.8,
       71.3, 65.8, 65.8, 61.8, 67.1, 64. , 65.5, 68.3, 66.2, 64. , 67.9,
       66.5, 65.7, 60.3, 63.1, 67.1, 58.6, 67. , 59.3, 62.8, 63.7, 62.4,
       63.3, 61.8, 68.2, 66.4, 66.4, 67.7])

In [20]:
np.save('./data.npy',data)
np.savetxt('./data.txt',data)

In [19]:
np.load('./data.npy')

array([66.5, 64.5, 58.5, 67.9, 62.5, 61.6, 63.5, 62.2, 68.6, 64.7, 67.5,
       60.9, 59.4, 62.1, 71.3, 59.7, 69.6, 64.6, 65.2, 57.5, 66.8, 63.9,
       66.7, 70.1, 65.3, 60.2, 61. , 59.9, 68.6, 67.1, 66.6, 66.8, 69.9,
       66.8, 66. , 63.4, 66.9, 62.3, 60.4, 62.7, 62.2, 65.4, 64. , 64.8,
       71.3, 65.8, 65.8, 61.8, 67.1, 64. , 65.5, 68.3, 66.2, 64. , 67.9,
       66.5, 65.7, 60.3, 63.1, 67.1, 58.6, 67. , 59.3, 62.8, 63.7, 62.4,
       63.3, 61.8, 68.2, 66.4, 66.4, 67.7])

In [21]:
np.loadtxt('./data.txt')

array([66.5, 64.5, 58.5, 67.9, 62.5, 61.6, 63.5, 62.2, 68.6, 64.7, 67.5,
       60.9, 59.4, 62.1, 71.3, 59.7, 69.6, 64.6, 65.2, 57.5, 66.8, 63.9,
       66.7, 70.1, 65.3, 60.2, 61. , 59.9, 68.6, 67.1, 66.6, 66.8, 69.9,
       66.8, 66. , 63.4, 66.9, 62.3, 60.4, 62.7, 62.2, 65.4, 64. , 64.8,
       71.3, 65.8, 65.8, 61.8, 67.1, 64. , 65.5, 68.3, 66.2, 64. , 67.9,
       66.5, 65.7, 60.3, 63.1, 67.1, 58.6, 67. , 59.3, 62.8, 63.7, 62.4,
       63.3, 61.8, 68.2, 66.4, 66.4, 67.7])

矩阵运算

In [22]:
X = np.array([[1,1,1],[2,-1,1],[3,1,-1]])
Y = np.array([8,8,2])
w = np.array(['x','y','z'])

# 矩阵运算 Xw = Y 进行求解w的未知数
# 即利用逆矩阵进行表示欲解方程
X_inv = np.linalg.inv(X)
np.dot(X_inv,Y)

array([2., 1., 5.])

numpy 排序

使用np.sort()是对对象中的数进行排序然后返回排序后的结果，并不改变对象本身
使用.sort()排序，没有返回值，因为是直接对对象本身进行了修改

部分排序
np.partition()