![](./blessing.jpg)

In [1]:
import numpy as np


In [2]:
nd1 = np.random.randint(0,150,size = (4,5))

nd2 = np.random.randint(0,150,size = (2,5))

nd3 = np.random.randint(0,150,size = (4,8))

display(nd1, nd2, nd3)

array([[114,  18,  88,   1,  18],
       [101,  74,  24,  53, 143],
       [ 55,  44,  21, 114, 125],
       [ 27,  13,  24, 143,   7]])

array([[ 61,  34,  23,  66, 148],
       [ 69, 118, 119, 111,  78]])

array([[ 26, 113, 149, 112, 133, 136,  92,   6],
       [ 48,  39,  98,  13, 129,  54,   6, 108],
       [141, 108,  59,  50,  61,  98, 136,  31],
       [ 82,  94,  99,  19,  94, 128,  75,  73]])

In [5]:
np.concatenate([nd1, nd3], axis = 1)

array([[114,  18,  88,   1,  18,  26, 113, 149, 112, 133, 136,  92,   6],
       [101,  74,  24,  53, 143,  48,  39,  98,  13, 129,  54,   6, 108],
       [ 55,  44,  21, 114, 125, 141, 108,  59,  50,  61,  98, 136,  31],
       [ 27,  13,  24, 143,   7,  82,  94,  99,  19,  94, 128,  75,  73]])

np.hstack 与 np.vstack
用于水平级联和垂直级联

In [8]:
np.hstack((nd1,nd3))
np.vstack((nd1,nd2))

array([[114,  18,  88,   1,  18],
       [101,  74,  24,  53, 143],
       [ 55,  44,  21, 114, 125],
       [ 27,  13,  24, 143,   7],
       [ 61,  34,  23,  66, 148],
       [ 69, 118, 119, 111,  78]])

与之类似的有
np.split
np.hsplit
np.vsplit
参数indices_or_sections表示切分为几份，或从何处开始切分

np.precentile()求解ndarray百分比数，如中位数50、最大值100